spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Aditya1711-tech/microservice-configuration
          clone-on-start: true
server:
  port: 8085
